### ISSUE TITLE
incorrect order

### ISSUE THREAD

**Issue by jamesdesmond** [AMDmi3/gopro-rename#5]
Hello, I have a directory of files where GH010155.mp4 and GH020155.mp4 are present, as well as ~15 other files.

I would expect the sorter to put these two mentioned files as the first two in the sorted list, but it does not. The second file is at the end of the dry-run output, and the first file is at the beginning which is not correct.

GH010155.MP4
20211228 08:58:48.mp4
GH010156.MP4
20211228 09:00:30.mp4
GH010157.MP4
20211228 09:01:19.mp4
GH010158.MP4
20211228 09:02:06.mp4
GH010159.MP4
20211228 09:03:26.mp4
GH010160.MP4
20211228 09:04:34.mp4
GH010161.MP4
20211228 09:05:18.mp4
GH010162.MP4
20211228 09:06:58.mp4
GH010163.MP4
20211228 09:07:29.mp4
GH010164.MP4
20211228 09:08:06.mp4
GH010165.MP4
20211228 09:09:33.mp4
GH010166.MP4
20211228 09:11:15.mp4
GH020155.MP4
20211228 09:11:39.mp4
GH020165.MP4
20211228 09:12:02.mp4

**Comment by AMDmi3** [comment]
What "sorter" do you refer to? Where's the output from? How did you run the script?

**Comment by AMDmi3** [comment]
Closing as invalid. Meanwhile, I've added support for `GH*` pattern.
